### ISSUE TITLE
Error: Attempt to invoke virtual method 'boolean com.swctools.enums.BuildingGeneric.isJunk()' on a null object reference

### ISSUE THREAD

**Issue by Ryesistance** [DaveCMo/Android-SWC-Tools#6]
Have been experiencing the above error message for the past few weeks when trying to change base layouts via layout manager. No junk present, looking for some guidance on if this is update related or if I need to change something on my end to get back up and running.

**Comment by capt-spats** [comment]
I know the issue is from the new banners.  I've been working around it using SWC Layout Manager v1.4 on my PC.  I exported all my layouts and use them in the SWC layout manager until Dave has time to update his tools.  I haven't been able to figure out a workaround for the Android-SWC-tools except not to add the banners to your bases.

**Comment by DaveCMo** [comment]
I need to sort out notifications for issues on this Git, thanks for raising guys. Hopefully you only know there was a stop gap release at https://github.com/DaveCMo/Android-SWC-Tools-Beta-Channel/releases/tag/3.0.0-beta3
